### ISSUE TITLE
Issue with loop in Python

### ISSUE THREAD

**Issue by paul-bren** [paul-bren/Python#1]
Hi All,

I'm new to Python and GitHub. If this is not the right area for this then please let me know. I'm having trouble with a for loop navigating through a list. The idea here is to print "True" when a consecutive set of numbers are found in the list however it shouldn't print true if the sequence contains less than 3 consecutive iterations.

For example:

list [1,2,3,7,8,10,11,12,15,16,22,23,24]

Ideally the program would say "You have 3 sequences in your list". In this case it would be (123), (10,11,12) and (22,23,24). Notice there are 2 other consecutive sets of numbers in the list (7,8) and (15,16) however the program should ignore them because it's less than 3 (as mentioned above). Please find code below however  I'm at a slight road block.  Appreciate any pointers you may have.

l=[180, 185, 193, 201, 202, 256, 280, 281, 290, 291, 300, 400, 401, 405]
count=0

for i in range(len(l)-1):
    if (l[i] + 1 == l[i+1]):
        count+=1
        if count >=3:
            print("iteration of 3")
        else:
            continue
    continue
        
print(count)

Thanks

**Comment by FerDi-Prodigy** [comment]
So what do u need actually?

**Comment by paul-bren** [comment]
Hi FerDi-Prodigy, thanks for replying. I got this sorted.
